# Generated by Django 4.2 on 2023-05-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_profile_orderentry_order_order_entries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_entries',
        ),
        migrations.AddField(
            model_name='order',
            name='order_entries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='shop.orderentry'),
        ),
    ]
