# Generated by Django 4.2 on 2023-05-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_order_entries_order_order_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_entries',
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_entry', to='shop.order'),
        ),
    ]
