# Generated by Django 4.2 on 2023-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_order_entries_alter_orderentry_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='shop.order'),
        ),
    ]
